name: 'apache-kafka-sample'

services:
  zookeeper01:
    container_name: confluentinc-cp-zookeeper01-container
    hostname: confluentinc-cp-zookeeper01
    image: confluentinc/cp-zookeeper01:dev
    build:
      context: .
      dockerfile: ./infra/docker/zookeeper/Dockerfile
      cache_from:
        - confluentinc/cp-zookeeper:cache
    environment:
      ZOOKEEPER_SERVER_ID: 1 # Zookeeperクラスタを構成する各サーバに一意に割り当てられる識別子（myid）
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000 # 2000ミリ秒
      ZOOKEEPER_INIT_LIMIT: 10 # Zookeeperクラスタの初期接続のタイムアウト値（tickTime単位なので、2000×10で20秒）
      ZOOKEEPER_SYNC_LIMIT: 5 # Zookeeperクラスタの同期のタイムアウト値（tickTime単位なので、2000×5で10秒）
      ZOOKEEPER_SERVERS: zookeeper01:2888:3888;zookeeper02:2888:3888;zookeeper03:2888:3888
    ports:
      - "2181:2181"
    volumes:
      - ./infra/docker/zookeeper/01/data:/var/lib/zookeeper/data
      - ./infra/docker/zookeeper/01/log:/var/lib/zookeeper/log
    networks:
      - apache-kafka-sample

  zookeeper02:
    container_name: confluentinc-cp-zookeeper02-container
    hostname: confluentinc-cp-zookeeper02
    image: confluentinc/cp-zookeeper02:dev
    build:
      context: .
      dockerfile: ./infra/docker/zookeeper/Dockerfile
      cache_from:
        - confluentinc/cp-zookeeper:cache
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 10
      ZOOKEEPER_SYNC_LIMIT: 5
      ZOOKEEPER_SERVERS: zookeeper01:2888:3888;zookeeper02:2888:3888;zookeeper03:2888:3888
    ports:
      - "2182:2181"
    volumes:
      - ./infra/docker/zookeeper/02/data:/var/lib/zookeeper/data
      - ./infra/docker/zookeeper/02/log:/var/lib/zookeeper/log
    networks:
      - apache-kafka-sample

  zookeeper03:
    container_name: confluentinc-cp-zookeeper03-container
    hostname: confluentinc-cp-zookeeper03
    image: confluentinc/cp-zookeeper03:dev
    build:
      context: .
      dockerfile: ./infra/docker/zookeeper/Dockerfile
      cache_from:
        - confluentinc/cp-zookeeper:cache
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 10
      ZOOKEEPER_SYNC_LIMIT: 5
      ZOOKEEPER_SERVERS: zookeeper01:2888:3888;zookeeper02:2888:3888;zookeeper03:2888:3888
    ports:
      - "2183:2181"
    volumes:
      - ./infra/docker/zookeeper/03/data:/var/lib/zookeeper/data
      - ./infra/docker/zookeeper/03/log:/var/lib/zookeeper/log
    networks:
      - apache-kafka-sample

  kafka01:
    container_name: confluentinc-cp-server01-container
    hostname: confluentinc-cp-server01
    image: confluentinc/cp-server01:dev
    build:
      context: .
      dockerfile: ./infra/docker/kafka/Dockerfile
      cache_from:
        - confluentinc/cp-server01:cache
    ports:
      - "9092:9092"
    restart: always
    environment:
      KAFKA_BROKER_ID: 1 # サーバ毎に定めたBroker ID（整数値）※Zookeeperのmyidと同じIDにする必要はない
      KAFKA_BROKER_ID_GENERATION_ENABLE: false # Kafkaが自動的にIDを付与する機能を無効にして手動でIDを設定する
      KAFKA_ZOOKEEPER_CONNECT: zookeeper01:2181,zookeeper02:2181,zookeeper03:2181 # BrokerがZookeeperへ接続する際の接続情報
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka01:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
    depends_on: # Zookeeperを先に起動させ、その後Brokerを起動
      - zookeeper01
      - zookeeper02
      - zookeeper03
    volumes:
      - ./infra/docker/kafka/01/data:/var/lib/kafka/data
    networks:
      - apache-kafka-sample

  kafka02:
    container_name: confluentinc-cp-server02-container
    hostname: confluentinc-cp-server02
    image: confluentinc/cp-server02:dev
    build:
      context: .
      dockerfile: ./infra/docker/kafka/Dockerfile
      cache_from:
        - confluentinc/cp-server02:cache
    ports:
      - "9093:9092"
    restart: always
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_BROKER_ID_GENERATION_ENABLE: false
      KAFKA_ZOOKEEPER_CONNECT: zookeeper01:2181,zookeeper02:2181,zookeeper03:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka02:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
    depends_on:
      - zookeeper01
      - zookeeper02
      - zookeeper03
    volumes:
      - ./infra/docker/kafka/02/data:/var/lib/kafka/data
    networks:
      - apache-kafka-sample

  kafka03:
    container_name: confluentinc-cp-server03-container
    hostname: confluentinc-cp-server03
    image: confluentinc/cp-server03:dev
    build:
      context: .
      dockerfile: ./infra/docker/kafka/Dockerfile
      cache_from:
        - confluentinc/cp-server03:cache
    ports:
      - "9094:9092"
    restart: always
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_BROKER_ID_GENERATION_ENABLE: false
      KAFKA_ZOOKEEPER_CONNECT: zookeeper01:2181,zookeeper02:2181,zookeeper03:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka03:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
    depends_on:
      - zookeeper01
      - zookeeper02
      - zookeeper03
    volumes:
      - ./infra/docker/kafka/03/data:/var/lib/kafka/data
    networks:
      - apache-kafka-sample

  producer-app:
    container_name: producer-app-container
    hostname: producer-app-server
    image: node/app:dev
    build:
      context: .
      dockerfile: ./infra/docker/node/Dockerfile
      cache_from:
        - node/app:cache
    tty: true
    volumes:
      - ./producer-app:/var/www/app:cached
    networks:
      - apache-kafka-sample

  consumer-app:
    container_name: consumer-app-container
    hostname: consumer-app-server
    image: node/app:dev
    build:
      context: .
      dockerfile: ./infra/docker/node/Dockerfile
      cache_from:
        - node/app:cache
    tty: true
    volumes:
      - ./consumer-app:/var/www/app:cached
    networks:
      - apache-kafka-sample

networks:
  apache-kafka-sample:
    driver: bridge
